name: action-flask-ci
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
#    - uses: ./action-a
#      env:
#        MY_NAME: "Mona"
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com

    - uses: actions/docker/cli@master
      with:
        args: build -t docker.pkg.github.com/hongkunyoo/action-flask/flask:${{ github.sha }} .

    - uses: actions/docker/cli@master
      with:
        args: push docker.pkg.github.com/hongkunyoo/action-flask/flask:${{ github.sha }}

    - uses: apex/actions/slack@master
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
