name: action-flask-ci
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com

    - uses: actions/docker/cli@master
      with:
        args: build -t docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:${{ github.sha }} .

    - uses: actions/docker/cli@master
      with:
        args: push docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:${{ github.sha }}


    - uses: Ilshidur/action-slack@master
      name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: ThisIsMyUsername # Optional.
        SLACK_CHANNEL: general # Optional.
        SLACK_OVERRIDE_MESSAGE: 'Custom message' # Optional.
      with:
        args: 'A new commit has been pushed.'
