name: action-flask-ci
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - name: checkout source code
      uses: actions/checkout@master


#    - name: checkout action chart
#      uses: actions/checkout@master
#      with:
#        repository: https://github.com/hongkunyoo/action-chart.git
#        token: ${{ secrets.DOCKER_PASSWORD }}
    - name: checkout action
      run: |
          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.DOCKER_PASSWORD }}@github.com/hongkunyoo/action-chart.git"
          git clone "${remote_repo}"

#    - name: Publish to Registry
#      uses: elgohr/Publish-Docker-Github-Action@master
#      with:
#        name: hongkunyoo/action-flask/myflaskplz:${{ github.sha }}
#        username: ${{ secrets.DOCKER_USER }}
#        password: ${{ secrets.DOCKER_PASSWORD }} 
#        registry: docker.pkg.github.com
#        dockerfile: Dockerfile

    - uses: Ilshidur/action-slack@master
      name: Slack notification-failure
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #SLACK_OVERRIDE_MESSAGE: 'Custom message' # Optional.
      with:
        args: 'A new commit has been failed.'
    - uses: Ilshidur/action-slack@master
      name: Slack notification-success
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #SLACK_OVERRIDE_MESSAGE: 'Custom message' # Optional.
      with:
        args: 'A new commit has been success.'
