name: action-flask-ci
#on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
#    - name: checkout source code
#      uses: actions/checkout@master
#
#    - name: Build the Docker image
#      run: docker build . -t docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:${{ github.sha }}
#
#    - name: pylint
#      run: docker run --entrypoint pylint docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:${{ github.sha }} --errors-only app.py
#
#    - name: pytest
#      run: docker run --entrypoint pytest docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:${{ github.sha }} test_case.py
#
#    - name: tag latest
#      run: docker tag docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:${{ github.sha }} docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:latest
#
#    - name: login
#      run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: push
      run: |
          echo "push success"
          #docker push docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:${{ github.sha }}
          #docker push docker.pkg.github.com/hongkunyoo/action-flask/myflaskplz:latest


    - name: checkout chart
      run: |
          remote_repo="https://${GITHUB_ACTOR}:${{ secrets.DOCKER_PASSWORD }}@github.com/hongkunyoo/action-chart.git"
          git clone "${remote_repo}"
          cd action-chart
          git checkout stage
          echo ${{ github.sha }} >> README.md
          echo "" >> README.md
          git config --local user.email "hongkunyoo@gmail.com"
          git config --local user.name "hongkunyoo"
          git commit -m "${{ github.sha }} plz $date" -a
          git push "${remote_repo}" HEAD:stage

    - uses: Ilshidur/action-slack@master
      name: Slack notification-failure
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #SLACK_OVERRIDE_MESSAGE: 'Custom message' # Optional.
      with:
        args: 'A new commit has been failed. ${{ github.sha }}'
    - uses: Ilshidur/action-slack@master
      name: Slack notification-success
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #SLACK_OVERRIDE_MESSAGE: 'Custom message' # Optional.
      with:
        args: 'A new commit has been success. ${{ github.sha }}'
