name: event test
on: 
  check_run:
    types: [created, rerequested, requested_action, completed]



jobs:
  build:
    name: build action
    runs-on: ubuntu-latest    
    steps:
    - run: |
        echo "$GITHUB_ACTION"
        echo "$GITHUB_EVENT_NAME"
        echo "$GITHUB_EVENT_PATH"
        cat "$GITHUB_EVENT_PATH"


