name: event test
on: 
- check_run
- check_suite
- commit_comment
- create
- delete
- deployment
- deployment_status
- fork
- gollum
- issue_comment
- issues
- label
- member
- milestone
- page_build
- project
- project_card
- project_column
- public
- pull_request
- pull_request_review
- pull_request_review_comment
- push
- release
- status
- watch

jobs:
  build:
    name: build action
    runs-on: ubuntu-latest    
    steps:
    - run: |
        echo "$GITHUB_ACTION"
        echo "$GITHUB_EVENT_NAME"
        echo "$GITHUB_EVENT_PATH"


